### ISSUE TITLE
Error Loading Page if open a new tab for story from Find a Story

### ISSUE THREAD

**Issue by rebeccacrawford** [ThreeMinuteLearning/my3ml#62]
From my teacher account i did 'find a story' and then opened up stories in a new tab, they would not load.

They load just fine if clicked on directly but if you do 'in a new tab' you get  https://*domain-name*/#/stories/130
in the url and

Error Loading Page
Sorry. That story couldn't be found.

**Comment by tekul** [comment]
This is because your login only applies within one tab. Since you aren't logged in in the new tab you can't see that story. Issue #15 is also relevant.

**Comment by rebeccacrawford** [comment]
Is there a way we can open up a story and be able to return to the find a story search results?

As a teacher, you may want to open a story in another window to have a look and then return to the original search.

**Comment by tekul** [comment]
See #16.
